version: '3.8'

x-common-variables: &common-variables
        TZ: "America/Los_Angeles"

services:
    db:
        image: postgres:13
        container_name: db
        restart: always
        ports:
            - "5432:5432"
        expose:
            - "5432"
        volumes:
            - "./postgresql:/var/lib/postgresql/data"
        environment:
            <<: *common-variables
            POSTGRES_DB: discordbot
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        networks:
            - bot-network

    bot:
        build: .
        container_name: bot
        restart: always
        volumes:
            - ".:/opt/DiscordBot"
        environment:
            <<: *common-variables
        depends_on:
            - "db"
        networks:
            - bot-network

networks:
    bot-network:
        driver: bridge
